name: data_science_minimal
channels:
  - conda-forge
  - defaults
dependencies:
  # notebook dependencies
  - statsmodels==0.14.0
  # - tensorflow==2.12.1

  # jupyter dependencies
  # ipykernel is needed to register the pip environment with jupyter
  - ipykernel==6.25.0
  # for correct rendering of widgets in jupyter
  - ipywidgets==8.1.0
  # auto register conda environments as ipython kernels in jupyter
  - nb_conda_kernels==2.3.1
  # notebook is required to export to pdf/html
  - notebook==7.0.3

  # vscode/codespaces dependencies
  # required by data wrangler extension
  - regex==2022.7.9
